//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasteless.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EAN()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int EANID { get; set; }
        public Nullable<int> FoodTypeID { get; set; }
        public string EAN_Value { get; set; }
        public double EAN_Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual FoodType FoodType { get; set; }
    }
}
