//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasteless.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EAN { get; set; }
        public string FoodType { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.Guid GUID { get; set; }
    
        public virtual User User { get; set; }
    }
}
